const CFG={
  url:'https://dinqlgaveujdeyisgpty.supabase.co',
  key:'sb_publishable_xFCEf-YDU-F8PJfuoxHD-Q_NlFAWl9N',
  activeFn:'https://dinqlgaveujdeyisgpty.supabase.co/functions/v1/staff-active-shift',
  managerFn:'https://dinqlgaveujdeyisgpty.supabase.co/functions/v1/manager-delete-shift'
};
const H={apikey:CFG.key,'Content-Type':'application/json'};
const OWNER_KEY='r971_shared_shift_owner_v1',EMP_KEY='r971_staff_employee_v1';
const SHIFTS={ca1:{name:'Ca 1',time:'05:00 - 11:00',start:300,end:660},ca2:{name:'Ca 2',time:'14:00 - 18:00',start:840,end:1080},ca3:{name:'Ca 3',time:'18:00 - 22:00',start:1080,end:1320}};
const $=id=>document.getElementById(id);
const moneyFmt=new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0});
let active=null,selectedShift='',managerPin='',managerAudit=[],managerAttendance=[],historyRows=[],debtRows=[],attendanceRows=[];
let pollBusy=false,fullBusy=false,elapsedTimer=null,deferredPrompt=null;

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return moneyFmt.format(Number(n)||0)}
function parseMoney(v){return Number(String(v||'').replace(/\D/g,''))||0}
function localDateKey(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function vnTime(iso){return new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(iso))}
function vnDate(iso){return new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(iso))}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2800)}
function currentEmployee(){return $('attendanceEmployee')?.value.trim()||$('employeeName')?.value.trim()||localStorage.getItem(EMP_KEY)||'Chưa ghi tên NV'}
function rememberEmployee(v){if(v){localStorage.setItem(EMP_KEY,v);if($('attendanceEmployee'))$('attendanceEmployee').value=v;if($('employeeName'))$('employeeName').value=v}}
function owner(){try{return JSON.parse(localStorage.getItem(OWNER_KEY)||'null')}catch{return null}}
function isOwner(){const o=owner();return !!(active&&o&&String(o.id)===String(active.id)&&o.token)}
function fmtInput(el){const n=parseMoney(el.value);el.value=n?new Intl.NumberFormat('vi-VN').format(n):''}

async function rest(path,opt={}){const r=await fetch(`${CFG.url}/rest/v1/${path}`,{...opt,headers:{...H,...(opt.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||`Lỗi ${r.status}`);return t?JSON.parse(t):null}
async function activeApi(body){const r=await fetch(CFG.activeFn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`Lỗi ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
async function managerApi(action,id='',extra={}){const r=await fetch(CFG.managerFn,{method:'POST',headers:{'Content-Type':'application/json','x-manager-pin':managerPin},body:JSON.stringify({action,id:String(id||''),...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Lỗi ${r.status}`);return d}

function rowToActive(r){if(!r)return null;return{id:r.id,dateKey:r.date_key,shiftKey:r.shift_key,shiftName:r.shift_name,scheduledTime:r.scheduled_time,employee:r.employee,startAt:r.start_at,totals:r.totals||{},entries:Array.isArray(r.entries)?r.entries:[]}}
async function refreshActive(){if(pollBusy)return;pollBusy=true;try{const rows=await rest('staff_active_shift?select=id,date_key,shift_key,shift_name,scheduled_time,employee,start_at,totals,entries,updated_at&singleton_id=eq.1');const next=rowToActive(rows?.[0]||null);const changed=JSON.stringify(next)!==JSON.stringify(active);active=next;if(!active&&owner())localStorage.removeItem(OWNER_KEY);if(changed)renderActive();updateRevenueMode()}catch(e){console.error(e)}finally{pollBusy=false}}
function renderActive(){const on=!!active;$('activeCard').classList.toggle('hidden',!on);$('startCard').classList.toggle('hidden',on);document.querySelectorAll('.shift').forEach(b=>b.disabled=on);if(!on){clearInterval(elapsedTimer);elapsedTimer=null;updateStartButton();return}
  $('activeTitle').textContent=active.shiftName;$('activeMeta').textContent=`${active.employee} · ${active.scheduledTime} · bắt đầu ${vnTime(active.startAt)}`;
  $('activeLockNotice').textContent=isOwner()?`✓ Đây là ca bạn đã bắt đầu. Mọi máy đang xem công khai diễn biến ${active.shiftName}.`:`🔒 ${active.employee} đang làm ${active.shiftName}. Không thể bắt đầu ca khác cho đến khi ca này kết thúc.`;
  const t=active.totals||{};const transfer=Number(t.transfer||0),cash=Number(t.cash||0),court=Number(t.courtRevenue||0),water=Number(t.waterRevenue||0);$('liveTransfer').textContent=money(transfer);$('liveCash').textContent=money(cash);$('liveCourt').textContent=money(court);$('liveWater').textContent=money(water);$('liveCollected').textContent=money(transfer+cash);$('liveRevenue').textContent=money(court+water);$('liveDiff').textContent=money(transfer+cash-court-water);
  const entries=active.entries||[];$('activeEntriesEmpty').classList.toggle('hidden',entries.length>0);$('activeEntries').innerHTML=entries.map(e=>{const p=[];if(e.transfer)p.push(`CK ${money(e.transfer)}`);if(e.cash)p.push(`TM ${money(e.cash)}`);if(e.courtRevenue)p.push(`Sân ${money(e.courtRevenue)}`);if(e.waterRevenue)p.push(`Nước ${money(e.waterRevenue)}`);return `<div class="row"><div class="row-main"><b>${esc(vnTime(e.at))} · ${esc(e.employee||active.employee)}</b><span>${p.join(' · ')}</span></div></div>`}).join('');
  $('finishShiftBtn').classList.toggle('hidden',!isOwner());updateElapsed();clearInterval(elapsedTimer);elapsedTimer=setInterval(updateElapsed,1000);updateStartButton();
}
function updateElapsed(){if(!active)return;const s=Math.max(0,Math.floor((Date.now()-new Date(active.startAt).getTime())/1000));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;$('elapsed').textContent=[h,m,x].map(v=>String(v).padStart(2,'0')).join(':')}
function updateRevenueMode(){$('revenueMode').textContent=active?`${active.shiftName} · ${active.employee}`:'Ngoài ca'}
function updateStartButton(){$('startShiftBtn').disabled=!selectedShift||!$('employeeName').value.trim()||!!active}

async function startShift(){await refreshActive();if(active)return toast(`${active.employee} đang làm ${active.shiftName}`);const employee=$('employeeName').value.trim();if(!employee||!selectedShift)return toast('Nhập tên và chọn ca');const s=SHIFTS[selectedShift];try{const d=await activeApi({action:'start',employee,shiftKey:selectedShift,shiftName:s.name,scheduledTime:s.time,dateKey:localDateKey()});active=rowToActive(d.active);localStorage.setItem(OWNER_KEY,JSON.stringify({id:active.id,token:d.token}));rememberEmployee(employee);selectedShift='';document.querySelectorAll('.shift').forEach(b=>b.classList.remove('selected'));renderActive();toast(`Đã bắt đầu ${active.shiftName}. Các máy khác đã bị khóa chọn ca.`)}catch(e){if(e.status===409&&e.data?.active){active=rowToActive(e.data.active);renderActive()}toast(e.message)} }
async function finishShift(){if(!active||!isOwner())return toast('Chỉ máy bắt đầu ca mới được kết thúc');if(!confirm(`Kết thúc ${active.shiftName} của ${active.employee}?`))return;try{const o=owner();await activeApi({action:'finish',id:active.id,token:o.token,note:''});localStorage.removeItem(OWNER_KEY);active=null;renderActive();await refreshAll();toast('Đã kết thúc ca. Tất cả máy có thể chọn ca mới.')}catch(e){toast(e.message)}}

async function addRevenue(){const transfer=parseMoney($('qTransfer').value),cash=parseMoney($('qCash').value),courtRevenue=parseMoney($('qCourt').value),waterRevenue=parseMoney($('qWater').value);if(!(transfer||cash||courtRevenue||waterRevenue))return toast('Hãy nhập ít nhất một khoản tiền');const employee=currentEmployee();rememberEmployee(employee);$('addRevenueBtn').disabled=true;try{const d=await activeApi({action:'public_add_entry',entry:{id:crypto.randomUUID(),employee,transfer,cash,courtRevenue,waterRevenue}});if(d.active){active=rowToActive(d.active);renderActive();toast(`Đã cộng vào ${active.shiftName}`)}else{const now=new Date();await rest('staff_revenue_entries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({date_key:localDateKey(now),employee,transfer,cash,court_revenue:courtRevenue,water_revenue:waterRevenue,shift_name:'Ngoài ca',source:'manual'})});toast('Đã lưu doanh thu ngoài ca')}['qTransfer','qCash','qCourt','qWater'].forEach(id=>$(id).value='');await refreshSummary()}catch(e){toast('Không lưu được doanh thu')}finally{$('addRevenueBtn').disabled=false}}

function vnClockParts(){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());const o={};parts.forEach(p=>o[p.type]=p.value);return{h:+o.hour,m:+o.minute,s:+o.second}}
function attendanceShift(){const p=vnClockParts(),mins=p.h*60+p.m;for(const [key,s] of Object.entries(SHIFTS)){if(mins>=s.start&&mins<=s.end){const late=mins>s.start+1;return{key,...s,late,lateMinutes:late?mins-s.start:0}}}return null}
function updateClock(){const p=vnClockParts();$('clockNow').textContent=[p.h,p.m,p.s].map(v=>String(v).padStart(2,'0')).join(':');const s=attendanceShift();$('attendancePreview').textContent=s?`${s.name} · ${s.late?`Trễ ${s.lateMinutes} phút`:'Đúng giờ'} · cần bật vị trí GPS`:'Ngoài giờ chấm công'}
async function punchAttendance(){const employee=$('attendanceEmployee').value.trim();if(!employee)return toast('Nhập tên nhân viên');const s=attendanceShift();if(!s)return toast('Ngoài giờ chấm công');if(!navigator.geolocation)return toast('Thiết bị không hỗ trợ vị trí');rememberEmployee(employee);$('attendanceBtn').disabled=true;navigator.geolocation.getCurrentPosition(async pos=>{try{const now=new Date();const row={employee,punched_at:now.toISOString(),date_key:localDateKey(now),shift_key:s.key,shift_name:s.name,scheduled_start:s.time.split(' - ')[0],scheduled_end:s.time.split(' - ')[1],status:s.late?'late':'on_time',late_minutes:s.lateMinutes,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy_m:pos.coords.accuracy};await rest('staff_attendance_records',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});toast(`Đã chấm ${s.name} · ${s.late?'Trễ':'Đúng giờ'}`);await refreshAttendance()}catch(e){toast(String(e.message).includes('duplicate')?'Nhân viên đã chấm ca này hôm nay':'Không lưu được chấm công')}finally{$('attendanceBtn').disabled=false}},err=>{$('attendanceBtn').disabled=false;toast(err.code===1?'Bạn chưa cấp quyền vị trí':'Không lấy được vị trí GPS')},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
async function refreshAttendance(){const date=$('attendanceDate').value||localDateKey();try{attendanceRows=await rest(`staff_attendance_records?select=*&date_key=eq.${encodeURIComponent(date)}&order=punched_at.desc`)||[];renderAttendance()}catch(e){console.error(e)}}
function renderAttendance(){const list=attendanceRows;$('attendanceEmpty').classList.toggle('hidden',list.length>0);$('attendanceList').innerHTML=list.map(r=>{const loc=r.latitude!=null&&r.longitude!=null?`📍 ${Number(r.latitude).toFixed(5)}, ${Number(r.longitude).toFixed(5)}`:'📍 Vị trí đã xóa';const st=r.status==='late'?`Trễ ${r.late_minutes||0} phút`:'Đúng giờ';return `<div class="row"><div class="row-main"><b>${esc(r.employee)} · ${esc(r.shift_name)}</b><span>${vnDate(r.punched_at)} · ${vnTime(r.punched_at)} · ${esc(st)}</span><small>${esc(loc)}</small></div></div>`}).join('')}

async function refreshHistory(){const date=$('historyDate').value||localDateKey();try{historyRows=await rest(`staff_shift_history?select=*&date_key=eq.${encodeURIComponent(date)}&order=start_at.desc`)||[];renderHistory()}catch(e){console.error(e)}}
function renderHistory(){const shift=$('historyShift').value;const list=historyRows.filter(r=>shift==='all'||r.shift_key===shift);$('historyEmpty').classList.toggle('hidden',list.length>0);$('historyList').innerHTML=list.map(r=>`<div class="row"><div class="row-main"><b>${esc(r.shift_name)} · ${esc(r.employee)}</b><span>${vnTime(r.start_at)} → ${vnTime(r.end_at)}</span><small>Doanh thu ${money(r.revenue_total)} · Thu ${money(r.collected_total)} · Chênh lệch ${money(r.difference)}</small></div></div>`).join('')}
async function refreshDebts(){try{debtRows=await rest('customer_debts?select=*&settled=eq.false&order=created_at.desc')||[];renderDebts()}catch(e){console.error(e)}}
function renderDebts(){const total=debtRows.reduce((a,x)=>a+Number(x.amount||0),0);$('debtTotal').textContent=money(total);$('debtEmpty').classList.toggle('hidden',debtRows.length>0);$('debtList').innerHTML=debtRows.map(d=>`<div class="row"><div class="row-main"><b>${esc(d.customer)} · ${money(d.amount)}</b><span>${esc(d.reason)} · ${esc(d.employee||'')} · ${esc(d.shift_name||'Ngoài ca')}</span><small>${vnDate(d.created_at)} ${vnTime(d.created_at)}</small></div><div class="row-actions"><button class="btn danger mini" data-debt-delete="${esc(d.id)}">Xóa</button></div></div>`).join('');document.querySelectorAll('[data-debt-delete]').forEach(b=>b.onclick=()=>deleteDebt(b.dataset.debtDelete))}
async function addDebt(){const customer=$('debtCustomer').value.trim(),reason=$('debtReason').value.trim(),amount=parseMoney($('debtAmount').value);if(!customer||!reason||!amount)return toast('Nhập đủ tên khách, nội dung và số tiền');const employee=currentEmployee();rememberEmployee(employee);try{const now=new Date();await rest('customer_debts',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:crypto.randomUUID(),date_key:localDateKey(now),customer,reason,amount,employee,shift_key:active?.shiftKey||'',shift_name:active?.shiftName||'Ngoài ca',created_at:now.toISOString(),settled:false})});$('debtCustomer').value='';$('debtReason').value='';$('debtAmount').value='';await refreshDebts();toast('Đã thêm khách nợ')}catch(e){toast('Không thêm được khách nợ')}}
async function deleteDebt(id){const d=debtRows.find(x=>String(x.id)===String(id));if(!d||!confirm(`Xóa khoản nợ của ${d.customer}?`))return;try{await rest(`customer_debts?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});await refreshDebts();toast('Đã xóa khách nợ')}catch(e){toast('Không xóa được khách nợ')}}

async function refreshSummary(){const date=$('summaryDate').value||localDateKey();try{const [hist,outside,act]=await Promise.all([rest(`staff_shift_history?select=transfer,cash,court_revenue,water_revenue&date_key=eq.${encodeURIComponent(date)}`),rest(`staff_revenue_entries?select=transfer,cash,court_revenue,water_revenue&date_key=eq.${encodeURIComponent(date)}`),rest('staff_active_shift?select=date_key,totals&singleton_id=eq.1')]);const sum={transfer:0,cash:0,court:0,water:0};(hist||[]).forEach(r=>{sum.transfer+=+r.transfer||0;sum.cash+=+r.cash||0;sum.court+=+r.court_revenue||0;sum.water+=+r.water_revenue||0});(outside||[]).forEach(r=>{sum.transfer+=+r.transfer||0;sum.cash+=+r.cash||0;sum.court+=+r.court_revenue||0;sum.water+=+r.water_revenue||0});const ar=act?.[0];if(ar&&ar.date_key===date){const t=ar.totals||{};sum.transfer+=+t.transfer||0;sum.cash+=+t.cash||0;sum.court+=+t.courtRevenue||0;sum.water+=+t.waterRevenue||0}$('sumTransfer').textContent=money(sum.transfer);$('sumCash').textContent=money(sum.cash);$('sumCourt').textContent=money(sum.court);$('sumWater').textContent=money(sum.water);$('sumRevenue').textContent=money(sum.court+sum.water)}catch(e){console.error(e)}}

function openManager(){const p=prompt('Nhập PIN Quản Lý');if(p===null)return;if(p!=='270523')return toast('PIN không đúng');managerPin=p;$('managerPanel').classList.remove('hidden');$('managerOpenBtn').classList.add('hidden');$('managerDate').value=localDateKey();refreshManager();toast('Đã mở Quản Lý')}
function lockManager(){managerPin='';$('managerPanel').classList.add('hidden');$('managerOpenBtn').classList.remove('hidden')}
async function refreshManager(){if(!managerPin)return;const date=$('managerDate').value||localDateKey();try{const [a,att,sh]=await Promise.all([managerApi('list_audit','',{date,limit:500}),rest(`staff_attendance_records?select=*&date_key=eq.${encodeURIComponent(date)}&order=punched_at.desc`),rest(`staff_shift_history?select=*&date_key=eq.${encodeURIComponent(date)}&order=start_at.desc`)]);managerAudit=a.rows||[];managerAttendance=att||[];renderAudit();renderManagerAttendance();renderManagerShifts(sh||[])}catch(e){toast('Không tải được dữ liệu quản lý')}}
function renderAudit(){const shift=$('managerShift').value;const sn=shift==='all'?'':SHIFTS[shift].name;const list=managerAudit.filter(x=>!sn||x.shift_name===sn||!x.shift_name);$('auditEmpty').classList.toggle('hidden',list.length>0);$('auditList').innerHTML=list.map(r=>{const d=r.details||{},p=[];[['transfer','CK'],['cash','TM'],['court_revenue','Sân'],['water_revenue','Nước'],['amount','Nợ'],['revenue_total','DT']].forEach(([k,n])=>{if(Number(d[k]||0))p.push(`${n} ${money(d[k])}`)});return `<div class="audit"><div class="audit-time">${vnTime(r.created_at)}</div><div class="audit-text"><b>${esc(r.action_type||'Thao tác')}${r.employee?` · ${esc(r.employee)}`:''}</b><span>${esc(r.description||'')}</span>${p.length?`<small>${p.join(' · ')}</small>`:''}</div></div>`}).join('')}
function renderManagerAttendance(){const shift=$('managerShift').value;const list=managerAttendance.filter(r=>shift==='all'||r.shift_key===shift);$('managerAttendanceEmpty').classList.toggle('hidden',list.length>0);$('managerAttendanceList').innerHTML=list.map(r=>`<div class="row"><div class="row-main"><b>${esc(r.employee)} · ${esc(r.shift_name)}</b><span>${vnTime(r.punched_at)} · ${r.status==='late'?`Trễ ${r.late_minutes||0} phút`:'Đúng giờ'}</span><small>${r.latitude!=null?`GPS ${Number(r.latitude).toFixed(5)}, ${Number(r.longitude).toFixed(5)}`:'Không còn GPS'}</small></div><div class="row-actions"><button class="btn danger mini" data-att-delete="${r.id}">Xóa chấm công</button></div></div>`).join('');document.querySelectorAll('[data-att-delete]').forEach(b=>b.onclick=()=>managerDeleteAttendance(b.dataset.attDelete))}
function renderManagerShifts(rows){window._managerShifts=rows;const shift=$('managerShift').value;const list=rows.filter(r=>shift==='all'||r.shift_key===shift);$('managerShiftEmpty').classList.toggle('hidden',list.length>0);$('managerShiftList').innerHTML=list.map(r=>`<div class="row"><div class="row-main"><b>${esc(r.shift_name)} · ${esc(r.employee)}</b><span>${vnTime(r.start_at)} → ${vnTime(r.end_at)}</span><small>Doanh thu ${money(r.revenue_total)}</small></div><div class="row-actions"><button class="btn danger mini" data-shift-delete="${esc(r.id)}">Xóa ca</button></div></div>`).join('');document.querySelectorAll('[data-shift-delete]').forEach(b=>b.onclick=()=>managerDeleteShift(b.dataset.shiftDelete))}
async function managerDeleteAttendance(id){const r=managerAttendance.find(x=>String(x.id)===String(id));if(!r||!confirm(`Xóa toàn bộ chấm công của ${r.employee}?\nGiờ chấm và vị trí GPS đều sẽ bị xóa.`))return;try{await managerApi('delete_attendance',id);await Promise.all([refreshManager(),refreshAttendance()]);toast('Đã xóa toàn bộ chấm công')}catch(e){toast('Không xóa được chấm công')}}
async function managerDeleteShift(id){if(!confirm('Xóa ca này khỏi lịch sử chung?'))return;try{await managerApi('delete_shift',id);await Promise.all([refreshManager(),refreshHistory(),refreshSummary()]);toast('Đã xóa ca')}catch(e){toast('Không xóa được ca')}}

async function refreshAll(){if(fullBusy)return;fullBusy=true;try{await Promise.allSettled([refreshActive(),refreshAttendance(),refreshHistory(),refreshDebts(),refreshSummary()]);if(managerPin)await refreshManager()}finally{fullBusy=false}}
function bind(){const emp=localStorage.getItem(EMP_KEY)||'';rememberEmployee(emp);const today=localDateKey();['attendanceDate','summaryDate','historyDate'].forEach(id=>$(id).value=today);$('todayLabel').textContent=new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());
  document.querySelectorAll('.money').forEach(el=>el.addEventListener('input',()=>fmtInput(el)));$('attendanceEmployee').addEventListener('input',e=>rememberEmployee(e.target.value.trim()));$('employeeName').addEventListener('input',e=>{rememberEmployee(e.target.value.trim());updateStartButton()});document.querySelectorAll('.shift').forEach(b=>b.onclick=()=>{selectedShift=b.dataset.shift;document.querySelectorAll('.shift').forEach(x=>x.classList.toggle('selected',x===b));updateStartButton()});
  $('attendanceBtn').onclick=punchAttendance;$('addRevenueBtn').onclick=addRevenue;$('startShiftBtn').onclick=startShift;$('finishShiftBtn').onclick=finishShift;$('addDebtBtn').onclick=addDebt;$('attendanceDate').onchange=refreshAttendance;$('summaryDate').onchange=refreshSummary;$('historyDate').onchange=refreshHistory;$('historyShift').onchange=renderHistory;$('managerOpenBtn').onclick=openManager;$('managerLockBtn').onclick=lockManager;$('managerDate').onchange=refreshManager;$('managerShift').onchange=refreshManager;
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
function boot(){bind();updateClock();setInterval(updateClock,1000);refreshAll();setInterval(refreshActive,2500);setInterval(()=>{if(document.visibilityState==='visible')refreshAll()},8000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshAll()});window.addEventListener('focus',refreshAll)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();